{% set name = "earthkit-data" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b7c5e841b25d8e578716cf7b1b1a78db152e8e27567456446081032e38b65618

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools >=61
    - setuptools-scm >=8
  run:
    - array-api-compat
    - cfgrib >=0.9.10.1
    - dask
    - deprecation
    - earthkit-geo >=0.2
    - earthkit-utils
    - eccodes >=2.35.0
    - entrypoints
    - filelock
    - jinja2
    - jsonschema
    - lru-dict
    - markdown
    - multiurl
    - netcdf4
    - pandas
    - pdbufr >=0.11
    - python >={{ python_min }}
    - python-eccodes >=1.7.0
    - pyyaml
    - requests
    - tqdm >=4.63
    - xarray >=0.19

test:
  requires:
    - python {{ python_min }}
  imports:
    - earthkit.data

about:
  home: https://github.com/ecmwf/earthkit-data
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  summary: A format-agnostic interface for geospatial data with a focus on meteorology and climate science.
  doc_url: https://earthkit-data.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/earthkit-data

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
    - JamesVarndell
